blueprint:
  name: Light Brightness From Sun Elevation
  description: >
    When a Zigbee/ZHA switch button is pressed, set a light's brightness based on a sensor value
    and only if the sun is below a selected dusk boundary or a custom elevation.
  domain: automation
  input:
    switch_device:
      name: Switch Device
      description: The Zigbee/ZHA switch to trigger on button press
      selector:
        device:
          integration: zha
    light_entity:
      name: Light
      description: The light to control
      selector:
        entity:
          domain: light
    sensor_entity:
      name: Sensor
      description: The sensor to check for threshold
      selector:
        entity:
          domain: sensor
    low_threshold:
      name: Low Threshold
      description: Value below which dim brightness is used
      default: -6
      selector:
        number:
          min: -100
          max: 100
          step: 1
    dim_brightness:
      name: Dim Brightness (%)
      default: 5
      selector:
        number:
          min: 1
          max: 100
          step: 1
    full_brightness:
      name: Full Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
    dusk_mode:
      name: Dusk Mode
      description: Select dusk type or custom elevation
      default: civil
      selector:
        select:
          options:
            - civil
            - nautical
            - astronomical
            - night
            - custom
    custom_elevation:
      name: Custom Elevation (degrees)
      description: Used only if dusk_mode = custom
      default: -6
      selector:
        number:
          min: -90
          max: 0
          step: 0.1

variables:
  dusk_elevation: >
    {% set mode = dusk_mode %}
    {% if mode == 'civil' %}-6
    {% elif mode == 'nautical' %}-12
    {% elif mode == 'astronomical' %}-18
    {% elif mode == 'night' %}-90
    {% elif mode == 'custom' %}{{ custom_elevation }}
    {% endif %}

trigger:
  - platform: device
    device_id: !input switch_device
    domain: zha
    type: press
    subtype: Up

condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: "{{ dusk_elevation }}"

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_entity
            below: !input low_threshold
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: !input dim_brightness
      default:
        - service: light.turn_on
          target:
            entity_id: !input light_entity
          data:
            brightness_pct: !input full_brightness
