blueprint:
  name: Light Brightness From Sun Elevation
  description: >
    When a Zigbee/ZHA switch button is pressed, set a light's brightness based on a sensor value
    and only if the sun is below a selected twilight boundary or a custom elevation.
  domain: automation
  input:
    switch_device:
      name: Switch Device
      description: The Zigbee/ZHA switch to trigger on button press
      selector:
        device:
          integration: zha
    light_entity:
      name: Light
      description: The light to control
      selector:
        entity:
          domain: light
    sensor_entity:
      name: Sensor
      description: The sensor to check for threshold
      selector:
        entity:
          domain: sensor
    low_threshold:
      name: Low Threshold
      description: Value below which dim brightness is used
      default: -6
      selector:
        number:
          min: -100
          max: 100
          step: 1
    dim_brightness:
      name: Dim Brightness (%)
      default: 5
      selector:
        number:
          min: 1
          max: 100
          step: 1
    full_brightness:
      name: Full Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
    twilight_mode:
      name: Twilight Mode
      description: Select twilight type or custom elevation
      default: civil
      selector:
        select:
          options:
            - "civil (-6째)"
            - "nautical (-12째)"
            - "astronomical (-18째)"
            - "custom"
    custom_elevation:
      name: Custom Elevation (degrees)
      description: Used only if twilight_mode = custom
      default: -6
      selector:
        number:
          min: -30
          max: 20
          step: 0.1

variables:
  twilight_elevation: >
    {% set mode = iif(input.twilight_mode, input.twilight_mode, 'civil (-6째)') %}
    {% if 'civil' in mode %}-6
    {% elif 'nautical' in mode %}-12
    {% elif 'astronomical' in mode %}-18
    {% elif 'custom' in mode %}{{ input.custom_elevation }}
    {% endif %}

trigger:
  - platform: device
    device_id: !input switch_device
    domain: zha
    type: press
    subtype: Up

condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: "{{ twilight_elevation }}"

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_entity
            below: !input low_threshold
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: !input dim_brightness
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_entity
        data:
          brightness_pct: !input full_brightness

mode: single
