blueprint:
  name: Light Brightness From Sun Elevation
  description: >
    When a Zigbee/ZHA switch button is pressed, set a light's brightness based on a sensor value
    and only if the sun is below a selected twilight boundary or a custom elevation.
  domain: automation
  input:
    switch_device:
      name: Switch Device
      description: The Zigbee/ZHA switch to trigger on button press
      selector:
        device:
          integration: zha
    light_entity:
      name: Light
      description: The light to control
      selector:
        entity:
          domain: light
    sensor_entity:
      name: Sensor
      description: The sensor to check for threshold
      selector:
        entity:
          domain: sensor
    dim_brightness:
      name: Dim Brightness (%)
      default: 5
      selector:
        number:
          min: 1
          max: 100
          step: 1
    full_brightness:
      name: Full Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
    twilight_mode:
      name: Twilight Mode
      description: Select twilight type or custom elevation
      default: civil
      selector:
        select:
          options:
            - "civil (-6°)"
            - "nautical (-12°)"
            - "astronomical (-18°)"
            - "custom"
    custom_elevation:
      name: Custom Elevation (degrees)
      description: Used only if twilight_mode = custom
      default: -6
      selector:
        number:
          min: -30
          max: 20
          step: 1

variables:
  twilight_elevation: >
    {% if 'civil' in input.twilight_mode %}-6
    {% elif 'nautical' in input.twilight_mode %}-12
    {% elif 'astronomical' in input.twilight_mode %}-18
    {% elif 'custom' in input.twilight_mode %}{{ input.custom_elevation }}
    {% endif %}

trigger:
  - platform: device
    device_id: !input switch_device
    domain: zha
    type: press
    subtype: Up

action:
  - choose:
      - conditions:
          - condition: template
            value_template: > 
              {{ state_attr('sun.sun', 'elevation') | float < twilight_elevation | float }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: !input dim_brightness
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_entity
        data:
          brightness_pct: !input full_brightness

mode: single
